services:
  - name: mysql
    type: web_service
    env: docker
    dockerfilePath: ./Dockerfile # Ruta al Dockerfile de MySQL
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: rootroot
      - key: MYSQL_DATABASE
        value: evaluacion360
      - key: MYSQL_USER
        value: my_user
      - key: MYSQL_PASSWORD
        value: rootroot
    ports:
      - port: 3306